[build-system]
requires = ["setuptools>=59.2.0", "numpy", "scipy"]
build-backend = "setuptools.build_meta"

[project]
name = "specrepro"
version = "0.0.1"
authors = [
  { name="Jonathan Lindbloom", email="jonathan@lindbloom.com" },
]
description = "Some codes for spectral reprojection."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
]
keywords = ["spectral reprojection", "Gibbs phenomenon", "Fourier approximation"]

[project.urls]
"Homepage" = "https://github.com/jlindbloom/spectral-reprojection"
"Bug Tracker" = "https://github.com/jlindbloom/spectral-reprojection/issues"


